application: twitter-atom
version: 2
runtime: python27
threadsafe: true
api_version: 1
default_expiration: 1d

libraries:
- name: django
  version: 1.3
- name: ssl
  version: latest

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /(generate|oauth_callback)
  script: main.application
  secure: always

- url: /atom
  script: main.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|doc|docs|pydocs|python3|ref|samples|tests)/.*
