# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: twitter-atom
runtime: python39
# default_expiration: 1d

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --workers 1 --threads 20 --timeout 60 -b :$PORT main:app

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  # max_idle_instances: 1
  max_concurrent_requests: 20
  # max_pending_latency: 100ms  # default is 30ms
  min_pending_latency: 2s  # default is 30ms
  max_pending_latency: 5s  # default is 30ms

handlers:

# static
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"
    Content-Security-Policy: "script-src https: localhost:8080 'unsafe-inline'; report-uri /csp-report;"
    Strict-Transport-Security: "max-age=16070400; includeSubDomains; preload"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"

# dynamic
- url: .*
  script: auto
  secure: always
